# Generated by Django 3.0.5 on 2022-01-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeAssignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Password',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
