# Generated by Django 3.0.5 on 2022-01-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeAssignment', '0002_auto_20220128_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='user',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='EmpID',
            field=models.IntegerField(null=True),
        ),
    ]
