# Generated by Django 3.0.5 on 2022-02-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeAssignment', '0005_auto_20220129_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigment',
            name='AssignmentNumber',
            field=models.IntegerField(null=True),
        ),
    ]
