# Generated by Django 3.0.5 on 2022-02-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeAssignment', '0007_auto_20220201_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigment',
            name='course',
        ),
    ]
