# Generated by Django 3.0.5 on 2022-02-02 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeAssignment', '0008_remove_assigment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigment',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='assigment',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RemoveField(
            model_name='newsbyteacher',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='users',
        ),
        migrations.RemoveField(
            model_name='uploadass',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='uploadass',
            name='userdetail',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='course',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='user',
        ),
        migrations.DeleteModel(
            name='Assigment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Newsbyteacher',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Uploadass',
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
